export type CaseType = {
  caseNo:string;
  useYn:'' | true | false;
  caseQstnCn:string;
  frstRegDt:string;
  caseTtl:string;
  comCdNm:string;
  path:string;
  srvcNo:string;
  inqCnt:number;
  upCtgryNo: string;
  ctgryNo: string;
  caseCn: string;
  sortSeq: number;
  regInstNo: string;
  atchFileId: string;
  caseSe: string;
  caseClsf: string;
  fileList: [];
  lwaCtgryNm: string;
  pdfId: string;
};

export type CaseTypeQuery = {
  startDate: string;
  endDate: string;
  keyword: string;
  keywordType: '' | 'CASE_TTL' | 'CASE_QSTN_CN';
  caseSe: string[];
  useYn: '' | true | false;
  page: number;
  size: number;
  inqCnt: number;
  instNo: string;
  desc: string;
  ctgryNo: string;
  tmpCtgryNo: string;
  pdfId: string;
  srvcNo: string;
  upCtgryNo: string;
};
